version: "3.7"

volumes:
  mongodb_data:
    driver: local

services:
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fake@23
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./conf/mongod.conf:/etc/mongo/mongod.conf
    command: --config /etc/mongo/mongod.conf

  mongo-express:
    image: mongo-express
    ports:
      - 7017:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: fake@23
      ME_CONFIG_MONGODB_SERVER: mongo
